# -*- mode: ruby -*-
# vi: set ft=ruby :


$script = <<-SCRIPT

export AUTOBAHN_TESTSUITE_VERSION='0.8.0'

echo [install packages]...
sudo apt update
sudo apt install -y python python-pip make php-cli && echo DONE || echo FAILED

echo [update pip]...
python -m pip install -U pip && echo DONE || echo FAILED

echo [install autobahntestsuite]...
python -m pip install autobahntestsuite==0.8.0 --user && echo DONE || echo FAILED

SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "=20180910.0.0"
  config.vm.box_check_update = false

  config.vm.synced_folder "../", "/vagrant"

  config.vm.provider "virtualbox" do |v|
  	v.memory = 4000
  end

  config.vm.provision "shell", inline: $script, privileged: false

end
